### ISSUE TITLE
feat：【PAC】跨项目复用构建资源池，支持Code配置

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10225]
```
resources:
  pools:
    - from: my_proj_1@poolA
      name: poolA-local
    - from: my_proj_1@poolB
      name: poolB-local

jobs:
  job1:
    runs-on:
      self-hosted: true
      pool-name: poolA-local
      agent-selector: [ windows ]
    steps:
      - run: echo "job1 in poolA-local"
  job2:
    runs-on:
      self-hosted: true
      pool-name: poolB-local
    steps:
      - run: echo "job2 in poolB-local"

```

1. 通过 resources.pools 申明构建资源池来源
- from: <管理构建机的蓝盾项目英文名>@<环境名称>
- name: <在当前 YAML 中使用时的名称>
2. 在 runs-on.pool-name 字段，使用 1 中定义好的name 引用即可
