### ISSUE TITLE
feat：第三方构建机 Job 间复用构建环境支持 Code 配置

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10254]
```
runs-on:
  self-hosted: true
  lock-resource-with: job_1
  agent-selector: [ windows ]
```

增加 lock-resource-with 关键字：
- 值为需要使用相同构建机的上游 Job id，仅支持单个 id
- 当self-hosted=true时生效
- 需检查值的有效性
