### ISSUE TITLE
feat：Git事件触发器自定义触发条件支持通过 Code 方式定义

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10497]
```
on:
  push:
    branches:
      - "*"
    custom-filter:
      url: <接口链接>
      credentials: <凭据ID>
```
url：第三方服务链接
credentials：token 凭据的ID
