### ISSUE TITLE
feat：P4触发器支持 Code 编写

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10551]
```
on:
  repo-name: 测试p4
  type: p4
  version: 2.*
  change-commit: 
    paths:
    - //depot/**
    paths-ignore:
    - ""
  change-content
    paths:
    - //depot/**
    paths-ignore:
    - ""
```
支持如下事件类型：
- change-commit
- change-content
- change-submit
- shelve-commit
- shelve-submit
