### ISSUE TITLE
feat：Git 事件触发器，自定义触发条件支持 Code 编写

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10552]
```
on:
  push:
    branches:
      - "*"
    custom-filter:
      url: <接口链接>
      credentials: <凭据ID>
    paths:
      - ".ci/trigger/t-custom.yml"
```
支持 custom-filte 关键字，支持指定 url 和 credentials
