### ISSUE TITLE
feat：Job 并发支持 Code 配置

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10860]
```
  job_private:
    name: 第三方构建机环境
    runs-on: 
      pool-name: my-pool
      self-hosted: true
      concurrency-limit-per-node: 2
      concurrency-limit-total: 5
      queue-timeout-minutes: 10
    steps:
      - run: echo hi, job_private
```
- concurrency-limit-per-node: 单节点并发限制
- concurrency-limit-total: 环境下所有节点上的总并发限制

原始需求：#9810
