### ISSUE TITLE
feat: UI方式下的「所有参数满足条件时执行」和「所有参数满足条件时不执行」转为Code 优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#10930]
UI方式下的「所有参数满足条件时执行」和「所有参数满足条件时不执行」转为Code 时，不要直接转为「表达式」，会让用户来回切换时有疑惑

语法如下：
```
- name: say hi
  if:
    mode: RUN_WHEN_ALL_PARAMS_MATCH
    params:
      a: hello
      b: 1
  jobs:
    check:
      steps:
      - run: ｜
          echo "a is ${{ variables.a }}"
          echo "b is ${{ variables.b }}"
- name: say hi2
  if:
    mode: NOT_RUN_WHEN_ALL_PARAMS_MATCH
    params:
      a: hello
      b: 1
  jobs:
    check:
      steps:
      - run: ｜
          echo "a is ${{ variables.a }}"
          echo "b is ${{ variables.b }}"

```
