### ISSUE TITLE
feat:研发商店组件支持一键发布

### ISSUE THREAD

**Issue by carlyin0801** [TencentBlueKing/bk-ci#11543]
**背景：**  目前公共构建机的环境可能不满足用户组件代码打包要求，用户想利用原来组件代码库打好包通过传包模式一键发布组件；但现在传包模式需要用户在工作台需要经过传包、多次录入信息等步骤，比较麻烦。

**措施：** 组件的所有基本信息都支持录入到bk-config.yml中，发布时通过从bk-config.yml中解析出基本信息来实现一键发布（**开发一个一键发布的build类接口，然后开发一个调用该build接口的插件提供给用户流水线使用**）。
组件新版的bk-config.yml结构如下：

```
storeCode: devxDemo # 应用标识【必填】
os:
  - packScriptPath: pack.bat # 打包脚本路径（相对于工程构建目录的相对路径，不填用平台默认的打包脚本）【非必填】
    packagePath: git-run.exe # 如果配了packScriptPath，packagePath为软件安装包相对于构建目录的位置； 否则packagePath为软件包相对于打的zip包中的位置【必填】
    osName: windows # 支持的操作系统名称【必填】
    osArch: x64 # 支持的操作系统CPU架构【非必填】
    signature: 
      originFilePaths : # 安装包中需要进行sha1签名的文件相对路径（该应用里面的子进程需要调用蓝盾的sdk，则该子进程对应的文件需要进行sha1签名以保证请求合法）【非必填】
        - git-bash.exe
        - git-cmd.exe
        - cmd/git.exe
    defaultFlag: true # 是否为默认环境信息（每种操作系统默认环境配置有且只有1个,没有匹配的操作系统名称和cpu架构就使用该默认环境配置）【必填】
releaseInfo: # 发布信息【非必填】
  projectCode: xxx # 调试项目标识【非必填】
  baseInfo:
    storeType: DEVX  # 应用类型【必填】
    name: 云研发测试应用 # 应用名称【必填】
    logoUrl: xxx  # logo地址【非必填】
    classifyCode: xxx  # 所属分类代码【必填】
    summary: xxx # 简介【必填】
    description: xxx # 描述【非必填】
    versionInfo:
      publisher: xxx  # 发布者【必填】
      releaseType: NEW # 发布类型【必填】
      version: 1.0.0 # 版本号【必填】
      versionContent: xxx  # 版本日志内容【必填】
    labelCodeList : # 标签标识列表【非必填】
       - xxx
       - xxx
    categoryCodeList : # 应用范畴标识列表【非必填】
       - xxx
       - xxx  	  
    extBaseInfo: {}  # 基础扩展信息【非必填】
    baseFeatureInfo: # 特性信息【非必填】
      type: xxx  # 组件类型【非必填】
      rdType: xxx  # 研发类型【非必填】
      extBaseFeatureInfo: {}  # 特性扩展信息【非必填】
    baseEnvInfos: # 环境信息列表【非必填】
      - language: xxx # 语言【非必填】
      - extBaseEnvInfo: {}  # 环境扩展信息【非必填】
```
说明：
1、logoUrl要传图片地址、description内容可能会包含图片或者其它文件
2、如果图片或者其它文件不是填远程地址，需要进行本地引用；那么在组件打包的zip文件里的根目录会有一个file文件夹，要引用的所有文件都放在这个目录下，在内容里通过${{indexFile("文件在file目录的相对路径")}}的表达式来引入文件，在解析bk-config.yml时需将该表达式里引入的文件上传到仓库并将该表达式替换成具体的文件链接地址。
3、description支持填md文件地址，在写入数据库时需将md文件内容转换成字符串存入。
4、用户录入的字段需做合法性校验，防止因为超长等原因写入数据库失败。
**5、releaseInfo里面除了storeType、versionInfo这二个字段每次发布都需要填，其它必填字段只在首次发布时才需要填，非首次发布不强制要求填，在一键发布时把非必填字段的值都继承上一次发布时录入的值进行处理。**
