### ISSUE TITLE
feat：执行时显示具体资源支持通过Code设置

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#11588]
<img width="400" alt="Image" src="https://github.com/user-attachments/assets/72998325-32ab-44a4-ba44-3cfaf666524d" />

1. 文案修改为：执行时显示具体资源
2. 增加关键字：show-runs-on， 布尔类型
```
    job_linux_2:
      name: 显式指定，默认配置
      runs-on: docker
      show-runs-on: true # 构建详情页，Job 名称是否展示实际运行的节点。true/false
      steps:
        - run: |
            echo hi, job_linux_2
```
