### ISSUE TITLE
【蓝盾Stream-无需评审会】feat：私有构建机使用镜像运行构建时，支持自定义Docker启动参数

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8461]
【背景】
目前 stream 已经支持在私有的 linux 构建机下使用 Docker 来运行构建任务
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/223434364-07475559-4451-4ce7-89bd-2fc59c7964e1.png">
但目前只支持用户指定 镜像和凭据，使用固定方式启动 Docker

未支持用户对 Docker 场景的一些灵活应用，比如：
场景一：用户需要实现 DooD ，希望能传入参数 -v /var/run/docker.sock:/var/run/docker.sock
场景二：用户需要使用 GPU 环境，希望能传入参数 --gpus all

【需求】
支持用户指定[启动 Docker 时的参数](https://docs.docker.com/engine/reference/commandline/run/)
1、按需支持，一期支持如下三个参数：
- --volume, -v：Bind mount a volume
- --gpus: GPU devices to add to the container (‘all’ to pass all GPUs)
- --mounts 

2、关键字为：options. volumes ， options. gpus 和 options. mounts
```yaml
    runs-on:
      self-hosted : true
      pool-name: my_pool_name
      container:
        image: xxx
        credentials: xxx
        options:
          volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
          gpus: all
          mounts: type=bind,source=xxxx,target=xxxx
```

3、保存流水线时，检查用户配置，若配置了不支持的启动参数，则保存失败并报错：
文案： [runs-on.container.options]Invalid options. Currently supports the following options: --gpus,  --volume/-v

注：以上选项不在公共构建机上支持，考虑如下方面：
- -v 选项能让用户 mount 母机上的任意目录，在公共构建机场景下不能支持，会越权
- 公共构建机没有 gpu 能力 

4、蓝盾json写法格式为在docker info下添加 options 如
```json
   "dockerInfo":{
      "options":{
         "volumes":[
            "/var/run/docker.sock:/var/run/docker.sock"
         ],
         "gpus": "all",
         "mounts": [
            "type=bind,source=xxxx,target=xxxx"
         ]
      }
   }
```
示例：如果需要在Docker里使用 docker命令，比如制作镜像等，**（以下都是以Docker默认安装路径为准）**

编排JSON：
```json

   "dockerInfo":{
      "options":{
         "volumes":[
            "/var/run/docker.sock:/var/run/docker.sock",
            "/usr/bin/docker:/usr/bin/docker"
         ]
      }
   }

```

PAC：
```yaml
    runs-on:
      self-hosted : true
      pool-name: my_pool_name
      container:
        image: xxx
        credentials: xxx
        options:
          volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
```
