### ISSUE TITLE
【stream】concurrency 和蓝盾功能对齐

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8631]
```
concurrency:
  group: ${{ ci.branch }}
  cancel-in-progress: false
  queue-length: 10
  queue-timeout-minutes: 1
```

- 增加 queue-length：最大排队任务数，1～20 之间的整数
- 增加 queue-timeout-minutes：排队超时时间，1～1440 之间的整数
