### ISSUE TITLE
feat：第三方构建机使用 docker 运行构建任务时，支持设置镜像拉取策略

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#8635]
```
  job_prM:
    runs-on:
      pool-name: thirdpart-docker
      self-hosted: true
      agent-selector: [ linux ]
      container:
        image: "xxx:1.0.3"
        image-pull-policy: always
```

增加拉取策略 image-pull-policy，可选值为：
- always：每次运行都拉取
- if-not-present：只有当镜像在本地不存在时才会拉取。
