### ISSUE TITLE
[stream] 优化远程模板凭据引用

### ISSUE THREAD

**Issue by yongyiduan** [TencentBlueKing/bk-ci#8667]
①保持和文档统一
```yaml
# 文档
personal-access-token: GIT_ACCESS_TOKEN
# 当前
personal-access-token: ${{ settings.GIT_ACCESS_TOKEN.access_token }}
```
② 解决跨模板凭据引用问题。
