### ISSUE TITLE
优化服务配置,配置项增加服务/模块名前缀

### ISSUE THREAD

**Issue by irwinsun** [TencentBlueKing/bk-ci#9334]
梳理配置项, 增加 微服务/模块前缀
例如:
```
process:
     abc:
       xyz: "__NAME__"

store:
   xxx:
      zzz: 123

```
