### ISSUE TITLE
feat：yaml 方式下，mr 触发器支持配置是否阻塞 mr 合并

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#9412]
和蓝盾mr 触发器功能对齐
语法如下：
```
on:
  mr:
    target-branches: [ "master" ]
    source-branches: 
      - feature*
    report-commit-check: true
    block-mr: true
```

新增两个关键字：
- report-commit-check，值为 true 时，上报 commit check 信息到工蜂
  - 缺省值为 true
- block-mr，值为 true 时，若流水线运行中或运行失败，阻塞 mr 运行
  - 缺省时，若项目上勾选了如下配置，则为 true，否则为 false
    <img width="150" alt="image" src="https://github.com/TencentBlueKing/bk-ci/assets/54432927/5ccea59c-c639-435f-9863-c5b2688f8fae">
