### ISSUE TITLE
【PAC】feat：推荐版本号支持通过 Code 定义

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#9819]
```
recommended-version:
  enabled: true
  allow-modify-at-startup: true
  major: 1
  minor: 2
  fix: 10
  build-no:
    initial-value: 0
    strategy: plus1-when-success / plus1-everytime / invariable
```
- 新增顶级关键字 recommended-version，缺省时默认不启用
- 包含如下属性：
  -  enabled，是否启用，缺省时默认不启用
  - allow-modify-at-startup，是否为入参
  - major：主版本
  - minor：特性版本
  - fix：修正版本
  - build-no：构建号，包含如下属性：
    - initial-value：初始值
    - strategy：自增策略，支持三种策略：
      -  plus1-when-success 成功时加1
      - plus1-everytime 每次加1
      - invariable：维持初始值不变
     
- 启用后，build-no 根据 initial-value 和 strategy 自增
