### ISSUE TITLE
feat：支持流水线指标监控

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#9860]
【目标】
采集流水线运行过程数据，方便用户按需定制监控和告警策略，协助用户分析流水线瓶颈，提高CI效率

【需求】
1、一期支持如下三个指标：
- 插件运行耗时
- 流水线运行耗时
- 流水线运行状态

2、按需开启，需要的项目才开启此功能

3、插件若不配置 step id ，则不上报对应数据

4、当前环境内，若未部署蓝鲸监控，不开启此功能

**Comment by yongyiduan** [comment]
产品讨论后决定使用 OpenTelemetry（OTel） 监视和观察流水线。行业案例有[Jenkins-opentelemetry](https://github.com/jenkinsci/opentelemetry-plugin)，[circle ci](https://github.com/DavidS/circleci-hook)，[Tekton ci](https://github.com/tektoncd/community/blob/main/teps/0124-distributed-tracing-for-tasks-and-pipelines.md), Drone CI等。由此可见流水线可观测能力的建设是必要的。
方案细节：
- 基础：opentelemetry-api，opentelemetry-sdk
- 定义[span](https://opentelemetry.io/docs/concepts/signals/traces/#spans)：
```yaml
bk-ci:
- start:
  - 排队
- build:
  - stage:
    - job:
      - 互斥组排队
      - 依赖等待
      - 构建机启动
      - step:
        - checkout
        - 插件执行
        - 串接子流水线
- end
```
