### ISSUE TITLE
【PAC】feat：流水线常量 Code 语法和规范

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-ci#9971]
Code语法：
```
variables:
  a: 1
  MY_CONST_1:
    value: 1 
    name: 我是预定义下拉可选值的字段
    const: true
    props:
      label: 可选值1 # [可选]
      type: selector
      options:
        - id: 1
          label: 正式环境
          description: 说明什么情况下发正式
      description: 这是个设置时可以下拉选择值的常量
```
命名规范：
- 由大写英文字母、数字和下划线组成，且以英文字母开头
- 不超过 64 字符

注意：
- const 属性 和 allow-modify-at-startup 属性互斥，若同时配置，校验不通过
- const 属性 设置为 true 时，readonly 一定为 true
